x-app-config: &app-config
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "8000:8000"
    environment:
      <<: [*app-config]
