exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
]

target-version = "py312"
line-length = 100
indent-width = 4

[lint]
preview = true
select = ["E303", "E4", "E7", "E9", "F", "I", "B", "COM", "PL", "UP"]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"app/tests/*.py" = ["E402", "PLR2004"]
"manage.py" = ["PLC0415"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
