name: CI

on: [push]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          make build

      - name: Run linters
        run: |
          make check

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          make build

      - name: Run tests
        run: |
          make test
